using Content.Client.Administration.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class OptionsMenu : DefaultWindow
{
    [Dependency] private IClientAdminManager _adminManager = default!;

    private readonly Dictionary<int, SidebarCategoryButton> _sidebarButtons = new();

    public OptionsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AddSidebarCategory(0, Loc.GetString("ui-options-tab-misc"));
        AddSidebarCategory(1, Loc.GetString("ui-options-tab-chat"));
        AddSidebarCategory(2, Loc.GetString("ui-options-tab-graphics"));
        AddSidebarCategory(3, Loc.GetString("ui-options-tab-controls"));
        AddSidebarCategory(4, Loc.GetString("ui-options-tab-audio"));
        AddSidebarCategory(5, Loc.GetString("ui-options-tab-accessibility"));
        AddSidebarCategory(6, Loc.GetString("ui-options-tab-admin"));

        Tabs.OnTabChanged += OnTabChanged;

        SelectTab(0);
        UpdateTabs();
    }

    private void AddSidebarCategory(int tabIndex, string title)
    {
        Tabs.SetTabTitle(tabIndex, title);
        var button = new SidebarCategoryButton(tabIndex, title, SelectTab);
        _sidebarButtons[tabIndex] = button;
        SidebarContainer.AddChild(button);
    }

    public void SelectTab(int index)
    {
        if (index < 0 || index >= Tabs.ChildCount)
            return;

        Tabs.CurrentTab = index;
        OnTabChanged(index);
    }

    private void OnTabChanged(int tabIndex)
    {
        foreach (var (index, button) in _sidebarButtons)
        {
            button.SetActive(index == tabIndex);
        }
    }

    public void UpdateTabs()
    {
        var isAdmin = _adminManager.IsAdmin(true);
        if (_sidebarButtons.TryGetValue(6, out var adminBtn))
            adminBtn.Visible = isAdmin;
        Tabs.SetTabVisible(6, isAdmin);

        GraphicsTab.Control.ReloadValues();
        MiscTab.Control.ReloadValues();
        ChatTab.Control.ReloadValues();
        AccessibilityTab.Control.ReloadValues();
        AudioTab.Control.ReloadValues();
        AdminOptionsTab.Control.ReloadValues();
    }

    private sealed class SidebarCategoryButton : Control
    {
        public readonly int TabIndex;
        public readonly Button MainButton;
        public readonly PanelContainer IndicatorBar;

        public SidebarCategoryButton(int tabIndex, string title, Action<int> onClick)
        {
            TabIndex = tabIndex;
            HorizontalExpand = true;
            MinHeight = 34;

            IndicatorBar = new PanelContainer
            {
                MinWidth = 4,
                MaxWidth = 4,
                VerticalExpand = true,
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#5288cc") },
                Visible = false,
            };

            MainButton = new Button
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                Text = title,
                ToggleMode = true,
                ClipText = true,
                TextAlign = Label.AlignMode.Left,
                Margin = new Thickness(4, 0, 0, 0),
            };

            MainButton.OnPressed += _ => onClick(TabIndex);

            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalExpand = true,
                SeparationOverride = 2,
            };

            box.AddChild(IndicatorBar);
            box.AddChild(MainButton);
            AddChild(box);
        }

        public void SetActive(bool active)
        {
            IndicatorBar.Visible = active;
            MainButton.Pressed = active;
        }
    }
}
