using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for check boxes and toggles in the options menu.
/// Features a two-column layout aligning with OptionSlider and OptionDropDown.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OptionCheckBox : Control
{
    public OptionCheckBox()
    {
        RobustXamlLoader.Load(this);

        NameLabel.MouseFilter = MouseFilterMode.Stop;
        NameLabel.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick && !Disabled)
            {
                CheckBox.Pressed = !CheckBox.Pressed;
                args.Handle();
            }
        };
    }

    /// <summary>
    /// The text describing what this check box controls.
    /// </summary>
    public string? Title
    {
        get => NameLabel.Text;
        set => NameLabel.Text = value;
    }

    /// <summary>
    /// Tooltip/description text for the option.
    /// </summary>
    public string? Description
    {
        get => ToolTip;
        set
        {
            ToolTip = value;
            NameLabel.ToolTip = value;
            CheckBox.ToolTip = value;
        }
    }

    /// <summary>
    /// Whether the check box is currently pressed / checked.
    /// </summary>
    public bool Pressed
    {
        get => CheckBox.Pressed;
        set => CheckBox.Pressed = value;
    }

    /// <summary>
    /// Whether user interaction with the check box is disabled.
    /// </summary>
    public bool Disabled
    {
        get => CheckBox.Disabled;
        set => CheckBox.Disabled = value;
    }

    public event Action<BaseButton.ButtonToggledEventArgs>? OnToggled
    {
        add => CheckBox.OnToggled += value;
        remove => CheckBox.OnToggled -= value;
    }

    public static implicit operator CheckBox(OptionCheckBox row) => row.CheckBox;
}
