using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for drop-downs in the options menu. Intended for use with <see cref="OptionsTabControlRow"/>.
/// </summary>
/// <seealso cref="OptionsTabControlRow.AddOptionDropDown{T}"/>
[GenerateTypedNameReferences]
public sealed partial class OptionDropDown : Control
{
    /// <summary>
    /// The text describing what this drop-down controls.
    /// </summary>
    public string? Title
    {
        get => NameLabel.Text;
        set => NameLabel.Text = value;
    }

    /// <summary>
    /// Tooltip text for the option, displayed when hovering anywhere over the row.
    /// </summary>
    public new string? ToolTip
    {
        get => base.ToolTip;
        set
        {
            base.ToolTip = value;
            NameLabel.ToolTip = value;
            Button.ToolTip = value;
        }
    }

    /// <summary>
    /// Tooltip/description text for the option.
    /// </summary>
    public string? Description
    {
        get => ToolTip;
        set => ToolTip = value;
    }
}
