using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for sliders in the options menu. Intended for use with <see cref="OptionsTabControlRow"/>.
/// Features hover highlight and accordion description.
/// </summary>
/// <seealso cref="OptionsTabControlRow.AddOptionSlider"/>
/// <seealso cref="OptionsTabControlRow.AddOptionPercentSlider"/>
[GenerateTypedNameReferences]
public sealed partial class OptionSlider : Control
{
    private static readonly StyleBoxFlat HoverStyle = new()
    {
        BackgroundColor = Color.FromHex("#1E2229"),
        BorderColor = Color.FromHex("#D48944"),
        BorderThickness = new Thickness(2, 0, 0, 0),
        ContentMarginLeftOverride = 4,
    };

    private string? _description;

    public OptionSlider()
    {
        RobustXamlLoader.Load(this);

        RowPanel.MouseFilter = MouseFilterMode.Pass;
        NameLabel.MouseFilter = MouseFilterMode.Pass;

        RowPanel.OnMouseEntered += _ => RowPanel.PanelOverride = HoverStyle;
        RowPanel.OnMouseExited += _ => RowPanel.PanelOverride = null;
    }

    /// <summary>
    /// The text describing what this slider controls.
    /// </summary>
    public string? Title
    {
        get => NameLabel.Text;
        set => NameLabel.Text = value;
    }

    /// <summary>
    /// Tooltip text for the option, displayed when hovering anywhere over the row.
    /// </summary>
    public new string? ToolTip
    {
        get => base.ToolTip;
        set
        {
            base.ToolTip = value;
            NameLabel.ToolTip = value;
            Slider.ToolTip = value;
            ValueLabel.ToolTip = value;
            RowPanel.ToolTip = value;
        }
    }

    /// <summary>
    /// Subtitle/description text for the option, displayed right under the title.
    /// </summary>
    public string? Description
    {
        get => _description ?? ToolTip;
        set
        {
            _description = value;
            DescriptionLabel.Text = value;
            DescriptionLabel.Visible = !string.IsNullOrWhiteSpace(value);
            ToolTip = value;
        }
    }
}
