using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for check boxes and toggles in the options menu.
/// Features modern toggle switch, clickable row, and hover-activated description accordion.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OptionCheckBox : Control
{
    private static readonly StyleBoxFlat HoverStyle = new()
    {
        BackgroundColor = Color.FromHex("#1E2229"),
        BorderColor = Color.FromHex("#E58229"),
        BorderThickness = new Thickness(2, 0, 0, 0),
        ContentMarginLeftOverride = 4
    };

    private string? _description;

    public OptionCheckBox()
    {
        RobustXamlLoader.Load(this);

        RowPanel.MouseFilter = MouseFilterMode.Pass;
        NameLabel.MouseFilter = MouseFilterMode.Pass;

        RowPanel.OnMouseEntered += _ =>
        {
            RowPanel.PanelOverride = HoverStyle;
            if (!string.IsNullOrWhiteSpace(_description))
                DescriptionLabel.Visible = true;
        };

        RowPanel.OnMouseExited += _ =>
        {
            RowPanel.PanelOverride = null;
            DescriptionLabel.Visible = false;
        };

        RowPanel.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick && !Disabled)
            {
                Pressed = !Pressed;
                args.Handle();
            }
        };

        ToggleSwitch.OnToggled += args =>
        {
            if (CheckBox.Pressed != args.Pressed)
                CheckBox.Pressed = args.Pressed;
            UpdateToggleVisual();
        };

        CheckBox.OnToggled += args =>
        {
            if (ToggleSwitch.Pressed != args.Pressed)
                ToggleSwitch.Pressed = args.Pressed;
            UpdateToggleVisual();
        };

        UpdateToggleVisual();
    }

    private void UpdateToggleVisual()
    {
        if (ToggleSwitch.Pressed)
        {
            ToggleSwitch.Text = Loc.GetString("ashfall-options-on");
            ToggleSwitch.Modulate = Color.FromHex("#FFAA44");
        }
        else
        {
            ToggleSwitch.Text = Loc.GetString("ashfall-options-off");
            ToggleSwitch.Modulate = Color.FromHex("#888899");
        }
    }

    /// <summary>
    /// The text describing what this check box controls.
    /// </summary>
    public string? Title
    {
        get => NameLabel.Text;
        set => NameLabel.Text = value;
    }

    /// <summary>
    /// Tooltip text for the option, displayed when hovering anywhere over the row.
    /// </summary>
    public new string? ToolTip
    {
        get => base.ToolTip;
        set
        {
            base.ToolTip = value;
            NameLabel.ToolTip = value;
            ToggleSwitch.ToolTip = value;
            CheckBox.ToolTip = value;
        }
    }

    /// <summary>
    /// Tooltip/description text for the option, displayed in accordion on hover.
    /// </summary>
    public string? Description
    {
        get => _description;
        set
        {
            _description = value;
            DescriptionLabel.Text = value;
            ToolTip = value;
        }
    }

    /// <summary>
    /// Whether the toggle switch is currently pressed / checked.
    /// </summary>
    public bool Pressed
    {
        get => CheckBox.Pressed;
        set
        {
            CheckBox.Pressed = value;
            ToggleSwitch.Pressed = value;
            UpdateToggleVisual();
        }
    }

    /// <summary>
    /// Whether user interaction with the check box is disabled.
    /// </summary>
    public bool Disabled
    {
        get => CheckBox.Disabled;
        set
        {
            CheckBox.Disabled = value;
            ToggleSwitch.Disabled = value;
        }
    }

    public event Action<BaseButton.ButtonToggledEventArgs>? OnToggled
    {
        add => CheckBox.OnToggled += value;
        remove => CheckBox.OnToggled -= value;
    }

    public static implicit operator CheckBox(OptionCheckBox row) => row.CheckBox;
}
