using Content.Client.Options.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for color sliders in the options menu. Intended for use with <see cref="OptionsTabControlRow"/>.
/// </summary>
/// <seealso cref="OptionsTabControlRow.AddOptionColorSlider"/>
[GenerateTypedNameReferences]
public sealed partial class OptionColorSlider : Control
{
    /// <summary>
    /// The text describing what this slider affects.
    /// </summary>
    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    /// <summary>
    /// The example text showing the current color of the slider.
    /// </summary>
    public string? Example
    {
        get => ExampleLabel.Text;
        set => ExampleLabel.Text = value;
    }

    /// <summary>
    /// Tooltip text for the option, displayed when hovering anywhere over the row.
    /// </summary>
    public new string? ToolTip
    {
        get => base.ToolTip;
        set
        {
            base.ToolTip = value;
            TitleLabel.ToolTip = value;
            Slider.ToolTip = value;
        }
    }

    /// <summary>
    /// Tooltip/description text for the option.
    /// </summary>
    public string? Description
    {
        get => ToolTip;
        set => ToolTip = value;
    }
}
