blank_issues_enabled: true
contact_links:
  - name: Предложить фичу
    url: https://discord.gg/rGvu9hKffJ
    about: Предложения по новым фичам присылайте на наш Discord-сервер (https://discord.gg/rGvu9hKffJ).
